# Bài tập thực hành tuần 2
> Họ và tên: Nguyễn Vạn Phúc Huy <br>
> MSSV: 23110163 <br>
> Lớp: 23TTH (Chiều thứ 6, ca 1)

In [46]:
# copy paste từ tuần 1 =)))
import numpy as np
import pandas as pd
import scipy
from sklearn.preprocessing import StandardScaler, KBinsDiscretizer
from sklearn.decomposition import PCA


### 1. Khoảng cách giữa các điểm trong dữ liệu số

Trước hết, chúng ta sẽ lấy dữ liệu từ file `ionosphere.data` trực tiếp theo đường link dưới đây.

In [47]:
link_hd_ko_che= r'https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data'
df = pd.read_csv(link_hd_ko_che, header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307,g
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712,g
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577,g
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243,g


Sau đó thực hiện lấy thông tin đặc trưng của bộ dữ liệu bằng hàm `describe()` và hàm `info()` của pandas.

In [48]:
display(df.info())
display(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       351 non-null    int64  
 1   1       351 non-null    int64  
 2   2       351 non-null    float64
 3   3       351 non-null    float64
 4   4       351 non-null    float64
 5   5       351 non-null    float64
 6   6       351 non-null    float64
 7   7       351 non-null    float64
 8   8       351 non-null    float64
 9   9       351 non-null    float64
 10  10      351 non-null    float64
 11  11      351 non-null    float64
 12  12      351 non-null    float64
 13  13      351 non-null    float64
 14  14      351 non-null    float64
 15  15      351 non-null    float64
 16  16      351 non-null    float64
 17  17      351 non-null    float64
 18  18      351 non-null    float64
 19  19      351 non-null    float64
 20  20      351 non-null    float64
 21  21      351 non-null    float64
 22  22

None

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
count,351.000000,351.0,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,...,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000
mean,0.891738,0.0,0.641342,0.044372,0.601068,0.115889,0.550095,0.119360,0.511848,0.181345,...,0.396135,-0.071187,0.541641,-0.069538,0.378445,-0.027907,0.352514,-0.003794,0.349364,0.014480
std,0.311155,0.0,0.497708,0.441435,0.519862,0.460810,0.492654,0.520750,0.507066,0.483851,...,0.578451,0.508495,0.516205,0.550025,0.575886,0.507974,0.571483,0.513574,0.522663,0.468337
min,0.000000,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,1.000000,0.0,0.472135,-0.064735,0.412660,-0.024795,0.211310,-0.054840,0.087110,-0.048075,...,0.000000,-0.332390,0.286435,-0.443165,0.000000,-0.236885,0.000000,-0.242595,0.000000,-0.165350
50%,1.000000,0.0,0.871110,0.016310,0.809200,0.022800,0.728730,0.014710,0.684210,0.018290,...,0.553890,-0.015050,0.708240,-0.017690,0.496640,0.000000,0.442770,0.000000,0.409560,0.000000
75%,1.000000,0.0,1.000000,0.194185,1.000000,0.334655,0.969240,0.445675,0.953240,0.534195,...,0.905240,0.156765,0.999945,0.153535,0.883465,0.154075,0.857620,0.200120,0.813765,0.171660
max,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000


Bỏ cột cuối (vì yêu cầu trong file thực hành nó vậy)

In [49]:
df.pop(df.columns[-1])
df

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,0.56811,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.20332,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,0.57528,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,1.00000,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,0.03286,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,0.95378,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.94520,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.93988,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,0.91050,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243


Khởi tạo các điểm point1, point2, point3 tương ướng là dòng 0, 1, 2 của array và tính chuẩn p = 1, 2, inf.

In [50]:
array = df.values
print(array)

point1 = array[0, :]
point2 = array[1, :]
point3 = array[2, :]

# p = 1
dist01_2 = np.linalg.norm(point1 - point2, 1)
dist01_3 = np.linalg.norm(point1 - point3, 1)

# p = 2
dist1_2 = np.linalg.norm(point1 - point2)
dist1_3 = np.linalg.norm(point1 - point3)

# p = inf 
dist11_2 = np.linalg.norm(point1 - point2, np.inf)
dist11_3 = np.linalg.norm(point1 - point3, np.inf)


print(dist1_2)
print(dist1_3)
print(dist01_2)
print(dist01_3)
print(dist11_2)
print(dist11_3)

[[ 1.       0.       0.99539 ... -0.54487  0.18641 -0.453  ]
 [ 1.       0.       1.      ... -0.06288 -0.13738 -0.02447]
 [ 1.       0.       1.      ... -0.2418   0.56045 -0.38238]
 ...
 [ 1.       0.       0.94701 ...  0.00442  0.92697 -0.00577]
 [ 1.       0.       0.90608 ... -0.03757  0.87403 -0.16243]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]]
2.7763589251571923
1.1697276018372824
13.080950000000001
5.359709999999999
1.12221
0.45772


#### Viết hàm tính các chuẩn p = 1, 2, inf cho 50 dòng đầu tiên của array trong mục 1


In [51]:
def calculate_distances(array):
    distances = []
    for i in range(50):
        for j in range(i + 1, 50):
            point_i = array[i, :]
            point_j = array[j, :]
            dist_p1 = np.linalg.norm(point_i - point_j, 1)
            dist_p2 = np.linalg.norm(point_i - point_j, 2)
            dist_pinf = np.linalg.norm(point_i - point_j, np.inf)
            distances.append((i, j, dist_p1, dist_p2, dist_pinf))
    return distances




distances = calculate_distances(array)
for dist in distances:
    print(f"Distance between point {dist[0]} and point {dist[1]}: p=1: {dist[2]}, p=2: {dist[3]}, p=inf: {dist[4]}")
    


Distance between point 0 and point 1: p=1: 13.080950000000001, p=2: 2.7763589251571923, p=inf: 1.12221
Distance between point 0 and point 2: p=1: 5.359709999999999, p=2: 1.1697276018372824, p=inf: 0.45772
Distance between point 0 and point 3: p=1: 21.057290000000002, p=2: 4.772562679724594, p=inf: 1.6053600000000001
Distance between point 0 and point 4: p=1: 6.21387, p=2: 1.3773473382919792, p=inf: 0.53525
Distance between point 0 and point 5: p=1: 15.166310000000001, p=2: 3.049072399681582, p=inf: 0.97202
Distance between point 0 and point 6: p=1: 7.577039999999999, p=2: 1.530471119753653, p=inf: 0.48305
Distance between point 0 and point 7: p=1: 22.28699, p=2: 4.803640361215647, p=inf: 1.85243
Distance between point 0 and point 8: p=1: 5.81361, p=2: 1.2050178826473905, p=inf: 0.39934000000000003
Distance between point 0 and point 9: p=1: 17.20169, p=2: 3.5643139959184293, p=inf: 1.3090600000000001
Distance between point 0 and point 10: p=1: 7.06033, p=2: 1.5055474137668332, p=inf: 0.

Do yêu cầu đề bài tập là viết hàm tính các chuẩn p = 1, 2, inf cho 50 dòng đầu tiên của array. Nên trong hàm 'calculate_distances' ta sẽ chạy vòng lặp for để tính khoảng cách giữa array với 50 dòng đầu tiên của array đó. 

```python
for i in range(50):
    for j in range(i + 1, 50):
         ... # Tính khoảng cách giữa dòng i và dòng j
    ...
```

Note: j bắt đầu từ i + 1 để tránh tính khoảng cách giữa một dòng với chính nó và tránh tính lại khoảng cách đã tính trước đó (do khoảng cách giữa dòng i và dòng j là như nhau với khoảng cách giữa dòng j và dòng i).

Tiếp theo chúng ta trích xuất dữ liệu của điểm i và j để tạo thành 2 vector `point_i` và `point_j`:

```python
point_i = array[i]
point_j = array[j]
```
Sau đó, chúng ta sẽ tính khoảng cách giữa `point_i` và `point_j` theo các chuẩn p = 1, 2, inf... bằng cách sử dụng hàm `np.linalg.norm(vector, ord=p)` của NumPy:
Với p = 1 là khoảng cách Manhattan, p = 2 là khoảng cách Euclidean, và p = inf là khoảng cách Chebyshev. Cụ thể:

```python
dist_p1 = np.linalg.norm(point_i - point_j, 1)  # Khoảng cách Manhattan
dist_p2 = np.linalg.norm(point_i - point_j, 2)  # Khoảng cách Euclidean
dist_pinf = np.linalg.norm(point_i - point_j, np.inf)  # Khoảng cách Chebyshev
```

Sau khi tính toán xong thì ta lưu lại vào `distances` để sau này có thể sử dụng hoặc in ra kết quả.

```python
distances.append((i, j, dist_p1, dist_p2, dist_pinf))
```

Cuối cùng ta được hàm `calculate_distances` như yêu cầu:
input: array (dữ liệu đã được xử lý)
output: distances (danh sách chứa khoảng cách giữa các điểm)


### 2. Độ đo tương đồng giữa các điểm trong tập dữ liệu phân loại

Trước hết, chúng ta sẽ lấy dữ liệu từ file `kddcup.data.corrected`

In [52]:
df=pd.read_csv('C:\\Users\\lenovo\\Downloads\\kddcup.data.corrected',header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,0,tcp,http,SF,215,45076,0,0,0,0,...,0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.0,normal.
1,0,tcp,http,SF,162,4528,0,0,0,0,...,1,1.0,0.0,1.00,0.00,0.0,0.00,0.0,0.0,normal.
2,0,tcp,http,SF,236,1228,0,0,0,0,...,2,1.0,0.0,0.50,0.00,0.0,0.00,0.0,0.0,normal.
3,0,tcp,http,SF,233,2032,0,0,0,0,...,3,1.0,0.0,0.33,0.00,0.0,0.00,0.0,0.0,normal.
4,0,tcp,http,SF,239,486,0,0,0,0,...,4,1.0,0.0,0.25,0.00,0.0,0.00,0.0,0.0,normal.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4898426,0,tcp,http,SF,212,2288,0,0,0,0,...,255,1.0,0.0,0.33,0.05,0.0,0.01,0.0,0.0,normal.
4898427,0,tcp,http,SF,219,236,0,0,0,0,...,255,1.0,0.0,0.25,0.05,0.0,0.01,0.0,0.0,normal.
4898428,0,tcp,http,SF,218,3610,0,0,0,0,...,255,1.0,0.0,0.20,0.05,0.0,0.01,0.0,0.0,normal.
4898429,0,tcp,http,SF,219,1234,0,0,0,0,...,255,1.0,0.0,0.17,0.05,0.0,0.01,0.0,0.0,normal.


Lấy các cột có thuộc tính là `object`

In [53]:
catagorical_columns = df.select_dtypes(include=['object']).columns
print("Categorical columns:", catagorical_columns)
categorical_data = df[catagorical_columns]
print("Categorical data:", categorical_data)

Categorical columns: Index([1, 2, 3, 41], dtype='int64')
Categorical data:           1     2   3        41
0        tcp  http  SF  normal.
1        tcp  http  SF  normal.
2        tcp  http  SF  normal.
3        tcp  http  SF  normal.
4        tcp  http  SF  normal.
...      ...   ...  ..      ...
4898426  tcp  http  SF  normal.
4898427  tcp  http  SF  normal.
4898428  tcp  http  SF  normal.
4898429  tcp  http  SF  normal.
4898430  tcp  http  SF  normal.

[4898431 rows x 4 columns]


Check những giá trị giống nhau và loại bỏ những cột có giá trị giống nhau ở tất cả các dòng (nếu có)

In [54]:
print(categorical_data.duplicated().sum())

df = categorical_data.drop_duplicates()
df

4897822


,1,2,3,41
0,tcp,http,SF,normal.
1288,tcp,http,S2,normal.
1484,tcp,http,S1,normal.
2062,tcp,smtp,SF,normal.
2067,udp,domain_u,SF,normal.
...,...,...,...,...
4574130,tcp,bgp,REJ,neptune.
4575586,tcp,Z39_50,REJ,neptune.
4578870,tcp,smtp,SF,neptune.
4579297,tcp,other,RSTO,neptune.


Lấy 100 dòng đầu tiên theo yêu cầu đề bài 

In [55]:
df_100 = df.head(100)
df_100

,1,2,3,41
0,tcp,http,SF,normal.
1288,tcp,http,S2,normal.
1484,tcp,http,S1,normal.
2062,tcp,smtp,SF,normal.
2067,udp,domain_u,SF,normal.
...,...,...,...,...
264244,tcp,ssh,SF,ipsweep.
264361,tcp,smtp,RSTO,normal.
264368,tcp,smtp,RSTO,ipsweep.
264396,tcp,domain,REJ,ipsweep.


Tiếp theo chúng ta tạo ma trận n x n để lưu trữ độ đo tương đồng giữa các điểm, trong đó n là số dòng của dữ liệu (ở đây là 100 do đề bài). 
- `overlap_matrix` để lưu trữ số lượng thuộc tính giống nhau giữa các điểm.
- `inv_freq_matrix` để lưu trữ độ đo tương đồng dựa trên tần suất nghịch đảo của các giá trị thuộc tính.


In [56]:
n = len(df_100)
overlap_matrix = np.zeros((n, n))
inv_freq_matrix = np.zeros((n, n))

Tiếp theo ta tính độ tương đồng giữa các điểm trong tập dữ liệu với công thức tổng quát như sau:

$$\text{Sim}(\overline{X}, \overline{Y} ) = \sum_{i=1}^{d} w_i \cdot \text{S}(x_i, y_i)$$
Với
- $w_i = \frac{1}{d}$ với i = 1, 2, ..., d
- $S(x_i, y_i)$ là hàm đánh giá sự giống nhau giữa thuộc tính $i$ được chia làm 2 loại là độ đo Overlap và độ đo dựa trên tần suất xuất hiện ngược


Ta tính độ đo Overlap với công thức: 

$$\text{Overlap}(x_i, y_i) = \text{S}(x_i, y_i) = \begin{cases} 1 & \text{nếu } x_i = y_i \\ 0 & \text{nếu } x_i \neq y_i \end{cases}$$


Cụ thể với code như sau:
`d = len(X)` để lấy số lượng thuộc tính của điểm X (và Y do |X| = |Y|).

Tiếp theo ta tính độ đo Overlap giữa X và Y bằng cách đếm số lượng thuộc tính giống nhau giữa hai điểm và chia cho tổng số thuộc tính d như công thức tổng quát sau khi thay $S(x_i, y_i)$ bằng công thức Overlap:
```python
sum = 0
for i in range(d):
    if X[i] == Y[i]:
        sum += 1
return sum / d
```


In [57]:
def overlap(X, Y):
    d = len(X)
    sum = 0
    for i in range(d):
        if X[i] == Y[i]:
            sum += 1
    return sum / d

Tương tự ta tính độ đo dựa trên tần suất xuất hiện ngược với công thức:

$$\text{Invfreq}(x_i, y_i) = \text{S}(x_i, y_i) = \begin{cases} \frac{1}{1 + \text{log}(f_i(x_i)) \cdot \text{log}(f_i(y_i))} & \text{nếu } x_i = y_i \\ 0 & \text{nếu } x_i \neq y_i \end{cases}$$

Note: $log$ ở đây là log cơ số 10, và $f_i(x_i)$ là tần suất xuất hiện của giá trị $x_i$ trong thuộc tính $i$ của tập dữ liệu

Tạo một hàm riêng để đếm và lấy tần suất xuất hiện của các giá trị thuộc tính trong tập dữ liệu để có thể sử dụng trong hàm tính độ đo dựa trên tần suất xuất hiện ngược.
Bằng cách ta dùng kỹ thuật dictionary để lưu tên của thuộc tính và tần suất xuất hiện của các giá trị thuộc tính đó trong tập dữ liệu.

```python
    for i in range(d):
        unique, counts = np.unique(data[:, i], return_counts=True)
        freq_dict = {} 
        for j in range(len(unique)):
            keyname = unique[j]       
            value = counts[j] 
            freq_dict[keyname] = value        
        freqs.append(freq_dict)
    return freqs
```

`unique` là mảng chứa các giá trị duy nhất của thuộc tính i, `counts` là mảng chứa số lần xuất hiện của từng giá trị đó. Ta tạo một dictionary `freq_dict` để lưu trữ tần suất xuất hiện của từng giá trị, với key là giá trị và value là số lần xuất hiện. Sau đó ta thêm `freq_dict` vào list `freqs` để có thể sử dụng sau này trong hàm tính độ đo dựa trên tần suất xuất hiện ngược.

In [ ]:
def freq(data):
    data = data.values
    freqs = []
    d = data.shape[1]
    
    for i in range(d):
        unique, counts = np.unique(data[:, i], return_counts=True)
        freq_dict = {} 
        for j in range(len(unique)):
            keyname = unique[j]       
            value = counts[j] 
            freq_dict[keyname] = value        
        freqs.append(freq_dict)
    return freqs

Cuối cùng ta áp dụng công thức tính độ đo dựa trên tần suất xuất hiện ngược vào hàm `inv_freq` bằng cách thay $S(x_i, y_i)$ bằng công thức đã cho và sử dụng tần suất xuất hiện từ `freqs` 

In [ ]:
def inv_freq(X, Y, freqs):
    d = len(X)
    sim = 0
    
    for i in range(d):
        if X[i] == Y[i]:
            f_x = freqs[i].get(X[i], 0)
            f_y = freqs[i].get(Y[i], 0)
            
            if f_x > 0 and f_y > 0:
                sim += 1 / (1 + (np.log(f_x) * np.log(f_y)))
    return sim / d

In [ ]:
freqs = freq(df_100)

for i in range(n):
    for j in range(n):
        if i == j:
            overlap_matrix[i, j] = 1.0 
            inv_freq_matrix[i, j] = 1.0
        else:
            overlap_matrix[i, j] = overlap(df_100.values[i], df_100.values[j])
            inv_freq_matrix[i, j] = inv_freq(df_100.values[i], df_100.values[j], freqs)

for i in range(n): 
    overlap_scores = overlap_matrix[i].copy()
    inv_freq_scores = inv_freq_matrix[i].copy()
    
    overlap_scores[i] = -1 
    inv_freq_scores[i] = -1
    
    best_overlap_idx = np.argmax(overlap_scores)
    best_inv_freq_idx = np.argmax(inv_freq_scores)
    
    print(f"\n df line {i}:")
    print(f" - Overlap ~= {best_overlap_idx}, v = {overlap_scores[best_overlap_idx]}")
    print(f" - Inverse freq ~= {best_inv_freq_idx}, v = {inv_freq_scores[best_inv_freq_idx]}")

[{'icmp': np.int64(5), 'tcp': np.int64(92), 'udp': np.int64(3)}, {'auth': np.int64(1), 'ctf': np.int64(2), 'daytime': np.int64(2), 'discard': np.int64(2), 'domain': np.int64(3), 'domain_u': np.int64(1), 'echo': np.int64(2), 'eco_i': np.int64(1), 'ecr_i': np.int64(3), 'finger': np.int64(3), 'ftp': np.int64(3), 'ftp_data': np.int64(6), 'gopher': np.int64(3), 'http': np.int64(9), 'link': np.int64(2), 'mtp': np.int64(3), 'name': np.int64(3), 'netstat': np.int64(2), 'ntp_u': np.int64(1), 'other': np.int64(2), 'pop_3': np.int64(1), 'private': np.int64(6), 'remote_job': np.int64(3), 'rje': np.int64(3), 'smtp': np.int64(6), 'ssh': np.int64(4), 'supdup': np.int64(1), 'systat': np.int64(2), 'telnet': np.int64(13), 'time': np.int64(3), 'urp_i': np.int64(1), 'whois': np.int64(3)}, {'OTH': np.int64(1), 'REJ': np.int64(25), 'RSTO': np.int64(15), 'RSTOS0': np.int64(5), 'RSTR': np.int64(12), 'S0': np.int64(6), 'S1': np.int64(4), 'S2': np.int64(1), 'S3': np.int64(3), 'SF': np.int64(28)}, {'buffer_overf